Доработка согласно ТЗ 6 спринта
Rbk-Galja/java-kanban pull request #1
Opened 2024-07-26 14:26 UTC by Rbk-Galja

Внесла изменения в класс InMemoryHistoryManager, дописала тесты согласно ТЗ

2024-07-26 16:06 UTC, YazykovMikhail requested changes

2024-07-26 16:06 UTC, YazykovMikhail commented on src/ru/practicum/vasichkina/schedule/manager/manager/InMemoryHistoryManager.java
> +    private List<Node> nodeList = new ArrayList<>();
эта переменная не нужна, такие же Ноды храняться и в  taskHistory

2024-07-26 16:06 UTC, YazykovMikhail commented on src/ru/practicum/vasichkina/schedule/manager/manager/InMemoryHistoryManager.java
> +        taskHistory.put(task.getId(), newNode);
linkLast - метод пр настройке ссылок, метод добавления это:
public void addTask(Task task) {
поэтому вынеси туда добавление 
taskHistory.put(task.getId(),  tail);

2024-07-26 16:06 UTC, YazykovMikhail commented on src/ru/practicum/vasichkina/schedule/manager/manager/InMemoryHistoryManager.java
> +    public void remove(int id) {
Хороший метод, молодец!

2024-07-26 16:06 UTC, YazykovMikhail commented on src/ru/practicum/vasichkina/schedule/manager/manager/InMemoryHistoryManager.java
>      public List<Task> getTasksHistory() {
private ArrayList<Task> getHistory() {
		ArrayList<Task> tasks = new ArrayList<>();

		Node node = head;
		while (node != null) {
			tasks.add(node.task);
			node = node.next;
		}
		return tasks;
	}
Не зря же мы ноды используешь, знаешь последовательно их

2024-07-29 15:58 UTC, Rbk-Galja commented on src/ru/practicum/vasichkina/schedule/manager/manager/InMemoryHistoryManager.java
> +        taskHistory.put(task.getId(), newNode);
Исправила

2024-07-29 15:58 UTC, Rbk-Galja commented on src/ru/practicum/vasichkina/schedule/manager/manager/InMemoryHistoryManager.java
> +    public void remove(int id) {
спасибо)

2024-07-30 13:08 UTC, YazykovMikhail approved these changes

2024-08-12 19:15 UTC, merged